server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/config/mybatis.cfg.xml
  type-aliases-package: common.pojo.*
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-ProviderMapper-1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.19.176:3306/common_account
    username: power_ad
    password: codespace0@#$
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200
  redis:
    database: 0
    timeout: 300ms
    host: 112.74.19.176
    port: 6300
    password: codespace0123HWiemri230xo43ie_________________
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        max-wait: 1000ms
        min-idle: 0
logging:
  config: classpath:log4j2/log4j2.cfg.xml
