server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://microservicecloud-eureka-1.com:7001/eureka/,http://microservicecloud-eureka-2.com:7002/eureka/,http://microservicecloud-eureka-3.com:7003/eureka/