server:
  port: 7003
eureka:
  instance:
    hostname: microservicecloud-eureka-3.com #eureka\u670D\u52A1\u7AEF\u5B9E\u4F8B\u540D\u79F0
  client:
    register-with-eureka: false #false\u4E0D\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    fetch-registry: false #false\u8868\u793A\u81EA\u5DF1\u662F\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u4E0D\u9700\u8981\u68C0\u7D22\u670D\u52A1
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #eureka\u5411\u5916\u66B4\u9732\u7684\u8BBF\u95EE\u5730\u5740\uFF0C\u4E3B\u8981\u7528\u6765\u4E0Eeureka\u5BA2\u6237\u7AEF\u8FDB\u884C\u4EA4\u4E92(\u5355\u673A)
      defaultZone: http://microservicecloud-eureka-1.com:7001/eureka/,http://microservicecloud-eureka-2.com:7002/eureka/
#  server: #\u7981\u7528\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F\uFF08\u4E0D\u63A8\u8350\u7981\u7528\uFF09
#    enable-self-preservation: false
